### ISSUE TITLE
SSL certificate for services.greenbutton.data has expired

### ISSUE THREAD

**Issue by adegwekar** [energyos/OpenESPI-GreenButtonCMDTest#179]
Hi,

The SSL certificate for services.greenbutton.org has expired as of 01/21/2015. As a result, API calls to the GreenButton sandbox are failing unless SSL certificate verification is turned off when making API calls. Please see attached snapshot of the certificate expiration. Could you please review and update the SSL certificate?
![screen shot 2015-01-24 at 3 29 38 pm](https://cloud.githubusercontent.com/assets/821664/5889487/da637700-a3de-11e4-8b04-084883fc2ff0.png)

Thanks,
Adi

**Comment by MartyBurns** [comment]
Thanks Adi.

We know. Should have resolved by Monday. 

Cheers,
Marty

**Comment by adegwekar** [comment]
Great, thanks for the prompt response.

**Comment by MartyBurns** [comment]
This is now complete
