### ISSUE TITLE
Add Resource for /oauth/authorize to support OAuth 2.0 CMD Certification

### ISSUE THREAD

**Issue by dfcoffin** [energyos/OpenESPI-GreenButtonCMDTest#63]
The CMD certification requires that the Data Custodian properly implement "The OAuth 2.0 Authorization Framework" [RFC6749].  To fully verify proper implementation of the RFC, the certification CMD testing needs to verify proper implementation of the /oauth/authorize endpoint.

**Comment by MartyBurns** [comment]
This is FB_14 of #50
